### ISSUE TITLE
Create an objectives roadmap

### ISSUE THREAD

**Issue by zachary-cauchi** [Ravenslofty/prussia#15]
With the steady progress on the given SVD file, and a newly-created [Peripheral Access Crate](https://github.com/zachary-cauchi/playstation2-pac-rs) as discussed in #13, having a place to track progress/completed tasks would be useful for all contributors and owners and allow for better coordination of tasks and what order to prioritise them. It doesn't need to be detailed or formal, even a single issue would help.

Definition of Done

* [x] Create a roadmap/task list to track important features, tasks, or similar objectives.
* [ ] Move in the existing feature goals from `README.md` into this new destination.
* [x] Establish a milestone and plan out the must-haves leading up to that milestone.

**Comment by Ravenslofty** [comment]
I have a few comments about the crate you made. 

- ideally it would have been kept inside the prussia repo like everything else is, because as a project everything is pretty heavily interlinked.
- could I have access to your repository please? that way we can reduce potential bus factor. 
- I wish you had asked me before slapping a GPL3+ license on `ps2.xml` when it's not solely your copyright. You've done a lot to help, and I do appreciate it, but now I'm in an awkward spot because I would have liked something more permissive.

Anyway, yes, I can create a roadmap for a minimum viable product (AKA drawing a triangle on the screen).

**Comment by zachary-cauchi** [comment]
Blast, I'm sorry about that. Got caught up in it. Maybe I can delete the repo and move the package here instead?

**Comment by zachary-cauchi** [comment]
* Reverted the license to match `prussia`'s (aka the Rust license, aka MIT or Apache v2).
* Relocated the crate source to a branch in my fork, will publish the pr soon.

Sorry again about the trouble with this.

**Comment by zachary-cauchi** [comment]
With PR #16 merged, I'm closing this issue.
